In [1]:
from functools import reduce
import re

import pandas as pd
import numpy as np

from src.categories import subcat_to_cat

import pickle

In [2]:
# preds_path_ls = [
#     ('raw 0 shot',   r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\Raw_0sh.bin'),
#     ('raw 5 shot',   r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\Raw_5sh.bin'),
#     ('LoRA 0 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\LoRA-cfg13_0sh.bin'),
#     ('LoRA 5 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\LoRA-cfg13_5sh.bin'),
#     ('GSOFT 0 shot', r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\GSOFT-cfg0_0sh.bin'),
#     ('GSOFT 5 shot', r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\GSOFT-cfg0_5sh.bin'),
# ]

# preds_path_ls = [
#     ('raw 0 shot',   r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\Raw_0sh.bin'),
#     ('raw 5 shot',   r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\Raw_5sh.bin'),
#     ('LoRA 0 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\LoRA-cfg17_0sh.bin'),
#     ('LoRA 5 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\LoRA-cfg17_5sh.bin'),
#     ('LoRA-code 0 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\LoRA-cfg18-code-ift-MMLU_0sh.bin'),
#     ('LoRA-code 5 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\LoRA-cfg18-code-ift-MMLU_5sh.bin'),
#     ('GSOFT-code 0 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\GSOFT-cfg3-code-ift-MMLU_0sh.bin'),
#     ('GSOFT-code 5 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\GSOFT-cfg3-code-ift-MMLU_5sh.bin'),
#     # ('LoRA-CR 0 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\LoRA-cfg18-OOD-MMLU_0sh.bin'),
#     # ('LoRA-CR 5 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\LoRA-cfg18-OOD-MMLU_5sh.bin'),
#     # ('DoRA-CR 0 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\DoRA-cfg18-OOD-MMLU_0sh.bin'),
#     # ('DoRA-CR 5 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\DoRA-cfg18-OOD-MMLU_5sh.bin'),
#     # ('GSOFT-CR 0 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\GSOFT-cfg3-OOD-MMLU_0sh.bin'),
#     # ('GSOFT-CR 5 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\GSOFT-cfg3-OOD-MMLU_5sh.bin'),
#     # ('VeRA-CR 0 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\VeRA-cfg1-OOD-MMLU_0sh.bin'),
#     # ('VeRA-CR 5 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\VeRA-cfg1-OOD-MMLU_5sh.bin'),
# ]

preds_path_ls = [
    ('Raw 1b',   r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\Raw_1b_5sh.bin'),
    ('LoRA_1b-CR',   r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\LoRA_1b-cfg1-CR_5sh.bin'),
    ('LoRA_1b-code st-2000',   r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\LoRA_1b-cfg1-st2000-MMLU_5sh.bin'),
    ('LoRA_1b-code st-4000',   r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\LoRA_1b-cfg1-st4000-MMLU_5sh.bin'),
    ('LoRA_1b-code st-6000',   r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\LoRA_1b-cfg1-st6000-MMLU_5sh.bin'),
]

In [3]:
preds_dfs = {}

for run_name, preds_path in preds_path_ls:
    with open(preds_path, 'rb') as f:
        preds_dfs[run_name] = pickle.load(file=f)

        print(f"{run_name:16}: {preds_dfs[run_name].shape=}")

Raw 1b          : preds_dfs[run_name].shape=(14042, 7)
LoRA_1b-CR      : preds_dfs[run_name].shape=(14042, 7)
LoRA_1b-code st-2000: preds_dfs[run_name].shape=(14042, 7)
LoRA_1b-code st-4000: preds_dfs[run_name].shape=(14042, 7)
LoRA_1b-code st-6000: preds_dfs[run_name].shape=(14042, 7)

In [4]:
idx = 6

print(preds_dfs['Raw 1b']['text'][idx])
print(preds_dfs['Raw 1b']['model_pred'][idx])

<|begin_of_text|><|start_header_id|>system<|end_header_id|>

The following are multiple choice questions (with answers) about abstract_algebra. Output 'A', 'B', 'C', or 'D'. Full answer not needed.<|eot_id|><|start_header_id|>user<|end_header_id|>

Find all c in Z_3 such that Z_3[x]/(x^2 + c) is a field.
A. 0
B. 1
C. 2
D. 3<|eot_id|><|start_header_id|>assistant<|end_header_id|>

B<|eot_id|><|start_header_id|>user<|end_header_id|>

Statement 1 | If aH is an element of a factor group, then |aH| divides |a|. Statement 2 | If H and K are subgroups of G then HK is a subgroup of G.
A. True, True
B. False, False
C. True, False
D. False, True<|eot_id|><|start_header_id|>assistant<|end_header_id|>

B<|eot_id|><|start_header_id|>user<|end_header_id|>

Statement 1 | Every element of a group generates a cyclic subgroup of the group. Statement 2 | The symmetric group S_10 has 10 elements.
A. True, True
B. False, False
C. True, False
D. False, True<|eot_id|><|start_header_id|>assistant<|end_header_id|>

C<|eot_id|><|start_header_id|>user<|end_header_id|>

Statement 1| Every function from a finite set onto itself must be one to one. Statement 2 | Every subgroup of an abelian group is abelian.
A. True, True
B. False, False
C. True, False
D. False, True<|eot_id|><|start_header_id|>assistant<|end_header_id|>

A<|eot_id|><|start_header_id|>user<|end_header_id|>

Find the characteristic of the ring 2Z.
A. 0
B. 3
C. 12
D. 30<|eot_id|><|start_header_id|>assistant<|end_header_id|>

A<|eot_id|><|start_header_id|>user<|end_header_id|>

Statement 1 | Every homomorphic image of a group G is isomorphic to a factor group of G. Statement 2 | The homomorphic images of a group G are the same (up to isomorphism) as the factor groups of G.
A. True, True
B. False, False
C. True, False
D. False, True<|eot_id|><|start_header_id|>assistant<|end_header_id|>

A<|eot_id|>
{'generated_text': 'C'}

In [5]:
# tmp_idxs = preds_dfs['Raw 1b 0 shot']['model_pred'].apply(
#     lambda p: re.match('[ABCD]', p['generated_text']) is not None
# )

# preds_dfs['Raw 1b 0 shot']['model_pred'][~tmp_idxs].shape

In [6]:
def get_category(subject):
    return subcat_to_cat[subject]

# OOD_part = re.compile('The correct answer is [ABCD]')
# OOD_part_len = len('The correct answer is ')

OOD_parts = [
    (re.compile('The correct answer is [ABCD]'), len('The correct answer is ')),
    (re.compile('The answer is [ABCD]'), len('The answer is ')),
    (re.compile('The solution is [ABCD]'), len('The solution is ')),
]

def get_pred(p):
    for OOD_part, OOD_part_len in OOD_parts:
        if OOD_part.search(p):
            return p[OOD_part_len]
    
    return p[0]

def processor(row: pd.DataFrame):
    generated_text = row['model_pred']['generated_text']
    generated_text = generated_text.strip()
    

    # generated_text	subject	pred	true	corr	category
    category = get_category(row['subject'])
    pred = get_pred(generated_text)
    true = chr(ord('A') + row['answer'])
    corr = int(pred == true)

    return {
        'generated_text': generated_text,
        'subject': row['subject'],
        'pred': pred,
        'true': true,
        'corr': corr,
        'category': category
    }

In [7]:
print(*preds_dfs.keys(), sep='\n')

Raw 1b
LoRA_1b-CR
LoRA_1b-code st-2000
LoRA_1b-code st-4000
LoRA_1b-code st-6000

In [8]:
for run_name in preds_dfs.keys():
    preds_dfs[run_name] = preds_dfs[run_name].apply(processor, axis=1, result_type='expand')

In [9]:
preds_dfs['Raw 1b'].head()

,generated_text,subject,pred,true,corr,category
0,C,abstract_algebra,C,B,0,STEM
1,C,abstract_algebra,C,C,1,STEM
2,C,abstract_algebra,C,D,0,STEM
3,C,abstract_algebra,C,B,0,STEM
4,To find the product of the given polynomials i...,abstract_algebra,T,B,0,STEM

In [10]:
preds_dfs['LoRA_1b-CR'].head()

,generated_text,subject,pred,true,corr,category
0,The correct answer is B. 4. The degree of a fi...,abstract_algebra,B,B,1,STEM
1,B,abstract_algebra,B,C,0,STEM
2,"The correct answer is C. 0,1. The only zeros o...",abstract_algebra,C,D,0,STEM
3,B,abstract_algebra,B,B,1,STEM
4,The correct answer is B. 6x^2 + 4x +,abstract_algebra,B,B,1,STEM

In [11]:
acc_by_subjects = pd.DataFrame({
    'subject': list(set.union(
        *map(
            lambda df: set(df['subject']),
            preds_dfs.values()
        )
    ))
})

print(f"Subjects: {acc_by_subjects['subject']}")

for run_name, preds_df in preds_dfs.items():
    acc_df = preds_df[['subject', 'corr']].groupby(['subject'], as_index=False).mean()
    acc_df.rename(columns={'corr': run_name}, inplace=True)

    acc_by_subjects = acc_by_subjects.merge(
        acc_df,
        left_on='subject',
        right_on='subject',
        how='right'
    )

Subjects: 0            high_school_computer_science
1                 high_school_mathematics
2                             human_aging
3                            formal_logic
4                       computer_security
5                     college_mathematics
6                  high_school_statistics
7                               sociology
8                   professional_medicine
9                         college_biology
10                              marketing
11                             prehistory
12                     clinical_knowledge
13               college_computer_science
14           high_school_european_history
15                 electrical_engineering
16                 elementary_mathematics
17                    high_school_physics
18                     conceptual_physics
19    high_school_government_and_politics
20                      logical_fallacies
21                                anatomy
22                 high_school_us_history
23              high_school_world_history
24                              astronomy
25                       college_medicine
26                             philosophy
27                       public_relations
28                        human_sexuality
29                          jurisprudence
30                               virology
31                         moral_disputes
32                    high_school_biology
33                       professional_law
34                       abstract_algebra
35                professional_psychology
36                          miscellaneous
37                             management
38                        world_religions
39                        business_ethics
40                        moral_scenarios
41                  high_school_chemistry
42             high_school_macroeconomics
43                  high_school_geography
44                 high_school_psychology
45                       machine_learning
46                       security_studies
47                           global_facts
48                              nutrition
49                professional_accounting
50                      college_chemistry
51                           econometrics
52                        college_physics
53                       medical_genetics
54                      international_law
55             high_school_microeconomics
56                      us_foreign_policy
Name: subject, dtype: object

In [12]:
acc_by_subjects

,subject,Raw 1b,LoRA_1b-CR,LoRA_1b-code st-2000,LoRA_1b-code st-4000,LoRA_1b-code st-6000
0,abstract_algebra,0.260000,0.270000,0.230000,0.260000,0.270000
1,anatomy,0.488889,0.474074,0.474074,0.488889,0.451852
2,astronomy,0.526316,0.381579,0.407895,0.388158,0.328947
3,business_ethics,0.500000,0.460000,0.410000,0.420000,0.410000
4,clinical_knowledge,0.486792,0.384906,0.430189,0.452830,0.479245
5,college_biology,0.430556,0.423611,0.430556,0.423611,0.402778
6,college_chemistry,0.270000,0.240000,0.260000,0.230000,0.270000
7,college_computer_science,0.240000,0.290000,0.350000,0.340000,0.280000
8,college_mathematics,0.240000,0.300000,0.290000,0.270000,0.250000
9,college_medicine,0.393064,0.312139,0.393064,0.381503,0.364162
10,college_physics,0.284314,0.196078,0.166667,0.156863,0.166667
11,computer_security,0.610000,0.530000,0.530000,0.570000,0.520000
12,conceptual_physics,0.438298,0.336170,0.404255,0.340426,0.302128
13,econometrics,0.307018,0.245614,0.254386,0.307018,0.236842
14,electrical_engineering,0.531034,0.441379,0.386207,0.393103,0.372414
15,elementary_mathematics,0.269841,0.314815,0.291005,0.256614,0.277778
16,formal_logic,0.317460,0.198413,0.261905,0.238095,0.214286
17,global_facts,0.290000,0.250000,0.230000,0.400000,0.400000
18,high_school_biology,0.451613,0.409677,0.367742,0.383871,0.400000
19,high_school_chemistry,0.339901,0.300493,0.280788,0.320197,0.349754
20,high_school_computer_science,0.390000,0.390000,0.280000,0.250000,0.280000
21,high_school_european_history,0.545455,0.496970,0.430303,0.448485,0.472727
22,high_school_geography,0.494949,0.398990,0.444444,0.484848,0.484848
23,high_school_government_and_politics,0.528497,0.440415,0.518135,0.466321,0.461140
24,high_school_macroeconomics,0.394872,0.274359,0.320513,0.364103,0.323077
25,high_school_mathematics,0.277778,0.255556,0.248148,0.259259,0.244444
26,high_school_microeconomics,0.411765,0.340336,0.348739,0.344538,0.378151
27,high_school_physics,0.298013,0.251656,0.271523,0.317881,0.317881
28,high_school_psychology,0.598165,0.449541,0.500917,0.495413,0.480734
29,high_school_statistics,0.291667,0.226852,0.250000,0.328704,0.282407
30,high_school_us_history,0.490196,0.431373,0.460784,0.441176,0.446078
31,high_school_world_history,0.565401,0.535865,0.459916,0.514768,0.506329
32,human_aging,0.475336,0.457399,0.434978,0.381166,0.385650
33,human_sexuality,0.541985,0.366412,0.396947,0.419847,0.404580
34,international_law,0.595041,0.504132,0.504132,0.520661,0.504132
35,jurisprudence,0.509259,0.416667,0.490741,0.462963,0.444444
36,logical_fallacies,0.503067,0.380368,0.392638,0.398773,0.435583
37,machine_learning,0.321429,0.348214,0.357143,0.348214,0.303571
38,management,0.485437,0.446602,0.485437,0.417476,0.446602
39,marketing,0.662393,0.564103,0.628205,0.628205,0.576923
40,medical_genetics,0.500000,0.450000,0.440000,0.440000,0.400000
41,miscellaneous,0.592593,0.556833,0.538953,0.504470,0.505747
42,moral_disputes,0.456647,0.390173,0.419075,0.375723,0.364162
43,moral_scenarios,0.274860,0.267039,0.307263,0.262570,0.263687
44,nutrition,0.565359,0.450980,0.509804,0.480392,0.467320
45,philosophy,0.475884,0.347267,0.421222,0.437299,0.437299
46,prehistory,0.503086,0.395062,0.472222,0.441358,0.453704
47,professional_accounting,0.361702,0.297872,0.290780,0.319149,0.301418
48,professional_law,0.358540,0.286832,0.295306,0.299870,0.279009
49,professional_medicine,0.426471,0.294118,0.352941,0.349265,0.386029
50,professional_psychology,0.433007,0.388889,0.398693,0.393791,0.387255
51,public_relations,0.427273,0.445455,0.445455,0.436364,0.427273
52,security_studies,0.489796,0.302041,0.387755,0.424490,0.469388
53,sociology,0.631841,0.477612,0.552239,0.512438,0.462687
54,us_foreign_policy,0.600000,0.550000,0.560000,0.520000,0.550000
55,virology,0.427711,0.361446,0.403614,0.361446,0.349398
56,world_religions,0.660819,0.596491,0.602339,0.614035,0.619883

In [13]:
acc_by_categories = pd.DataFrame({
    'category': list(set.union(
        *map(
            lambda df: set(df['category']),
            preds_dfs.values()
        )
    ))
})

for run_name, preds_df in preds_dfs.items():
    acc_df = preds_df[['category', 'corr']].groupby(['category'], as_index=False).mean()
    acc_df.rename(columns={'corr': run_name}, inplace=True)

    acc_by_categories = acc_by_categories.merge(
        acc_df,
        left_on='category',
        right_on='category',
        how='right'
    )

In [14]:
acc_by_categories.loc[:, list(filter(
    lambda s: ('5 shot' not in s),
    acc_by_categories.columns
))]

,category,Raw 1b,LoRA_1b-CR,LoRA_1b-code st-2000,LoRA_1b-code st-4000,LoRA_1b-code st-6000
0,STEM,0.358516,0.326706,0.321074,0.322730,0.313453
1,humanities,0.414665,0.348990,0.370882,0.361955,0.356004
2,"other (business, health, misc.)",0.502468,0.436151,0.453732,0.444170,0.439852
3,social sciences,0.488463,0.385115,0.424114,0.428339,0.419240

In [15]:
acc_by_categories.loc[:, list(filter(
    lambda s: ('0 shot' not in s),
    acc_by_categories.columns
))]

,category,Raw 1b,LoRA_1b-CR,LoRA_1b-code st-2000,LoRA_1b-code st-4000,LoRA_1b-code st-6000
0,STEM,0.358516,0.326706,0.321074,0.322730,0.313453
1,humanities,0.414665,0.348990,0.370882,0.361955,0.356004
2,"other (business, health, misc.)",0.502468,0.436151,0.453732,0.444170,0.439852
3,social sciences,0.488463,0.385115,0.424114,0.428339,0.419240

In [16]:
total_res = pd.DataFrame(columns=['run_name', 'accuracy', 'correctness'])

for run_name, preds_df in preds_dfs.items():
    total_accuracy = preds_df['corr'].mean()
    total_correctness = (preds_df['pred'].isin(['A', 'B', 'C', 'D'])).mean()

    total_res = pd.concat([
        total_res,
        pd.DataFrame({
            'run_name': [run_name],
            'accuracy': [total_accuracy],
            'correctness': [total_correctness],
        })
    ])

C:\Users\Vladimir\AppData\Local\Temp\ipykernel_13688\1869384032.py:7: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  total_res = pd.concat([

In [17]:
total_res

               run_name  accuracy  correctness
0                Raw 1b  0.439040     0.997935
0            LoRA_1b-CR  0.372240     0.996724
0  LoRA_1b-code st-2000  0.390970     0.997223
0  LoRA_1b-code st-4000  0.387053     0.999145
0  LoRA_1b-code st-6000  0.380074     0.999288