In [1]:
from functools import reduce
import re

import pandas as pd
import numpy as np

from src.categories import subcat_to_cat

import pickle

In [2]:
# preds_path_ls = [
#     ('raw 0 shot',   r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\Raw_0sh.bin'),
#     ('raw 5 shot',   r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\Raw_5sh.bin'),
#     ('LoRA 0 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\LoRA-cfg13_0sh.bin'),
#     ('LoRA 5 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\LoRA-cfg13_5sh.bin'),
#     ('GSOFT 0 shot', r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\GSOFT-cfg0_0sh.bin'),
#     ('GSOFT 5 shot', r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\GSOFT-cfg0_5sh.bin'),
# ]

preds_path_ls = [
    ('raw 0 shot',   r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\Raw_0sh.bin'),
    ('raw 5 shot',   r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\Raw_5sh.bin'),
    ('LoRA 0 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\LoRA-cfg17_0sh.bin'),
    ('LoRA 5 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\LoRA-cfg17_5sh.bin'),
    ('LoRA-OOD 0 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\LoRA-cfg18-OOD-MMLU_0sh.bin'),
    ('LoRA-OOD 5 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\LoRA-cfg18-OOD-MMLU_5sh.bin'),
    # ('GSOFT-OOD 0 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\GSOFT-cfg3-OOD-MMLU_0sh.bin'),
    ('GSOFT-OOD 5 shot',  r'C:\Users\Vladimir\PycharmProjects\OrthogonalFineTune\test_preds\GSOFT-cfg3-OOD-MMLU_5sh.bin'),
]

In [3]:
preds_dfs = {}

for run_name, preds_path in preds_path_ls:
    with open(preds_path, 'rb') as f:
        preds_dfs[run_name] = pickle.load(file=f)

        print(f"{run_name:16}: {preds_dfs[run_name].shape=}")

raw 0 shot      : preds_dfs[run_name].shape=(14042, 6)
raw 5 shot      : preds_dfs[run_name].shape=(14042, 6)
LoRA 0 shot     : preds_dfs[run_name].shape=(14042, 6)
LoRA 5 shot     : preds_dfs[run_name].shape=(14042, 6)
LoRA-OOD 0 shot : preds_dfs[run_name].shape=(14042, 7)
LoRA-OOD 5 shot : preds_dfs[run_name].shape=(14042, 7)
GSOFT-OOD 5 shot: preds_dfs[run_name].shape=(14042, 7)

In [4]:
idx = 23

print(preds_dfs['GSOFT-OOD 5 shot']['text'][idx])
print(preds_dfs['GSOFT-OOD 5 shot']['model_pred'][idx])

<|begin_of_text|><|start_header_id|>system<|end_header_id|>

The following are multiple choice questions (with answers) about abstract_algebra. Output 'A', 'B', 'C', or 'D'. Full answer not needed.<|eot_id|><|start_header_id|>user<|end_header_id|>

Find all c in Z_3 such that Z_3[x]/(x^2 + c) is a field.
A. 0
B. 1
C. 2
D. 3<|eot_id|><|start_header_id|>assistant<|end_header_id|>

B<|eot_id|><|start_header_id|>user<|end_header_id|>

Statement 1 | If aH is an element of a factor group, then |aH| divides |a|. Statement 2 | If H and K are subgroups of G then HK is a subgroup of G.
A. True, True
B. False, False
C. True, False
D. False, True<|eot_id|><|start_header_id|>assistant<|end_header_id|>

B<|eot_id|><|start_header_id|>user<|end_header_id|>

Statement 1 | Every element of a group generates a cyclic subgroup of the group. Statement 2 | The symmetric group S_10 has 10 elements.
A. True, True
B. False, False
C. True, False
D. False, True<|eot_id|><|start_header_id|>assistant<|end_header_id|>

C<|eot_id|><|start_header_id|>user<|end_header_id|>

Statement 1| Every function from a finite set onto itself must be one to one. Statement 2 | Every subgroup of an abelian group is abelian.
A. True, True
B. False, False
C. True, False
D. False, True<|eot_id|><|start_header_id|>assistant<|end_header_id|>

A<|eot_id|><|start_header_id|>user<|end_header_id|>

Find the characteristic of the ring 2Z.
A. 0
B. 3
C. 12
D. 30<|eot_id|><|start_header_id|>assistant<|end_header_id|>

A<|eot_id|><|start_header_id|>user<|end_header_id|>

The set of all nth roots of unity under multiplication of complex numbers form a/an
A. semi group with identity
B. commutative semigroups with identity
C. group
D. abelian group<|eot_id|><|start_header_id|>assistant<|end_header_id|>

D<|eot_id|>
{'generated_text': 'C'}

In [5]:
preds_dfs['GSOFT-OOD 5 shot']['model_pred'].apply(
    lambda p: p['generated_text'][0]
).value_counts()

model_pred
B    3974
C    3664
A    3439
D    2963
T       2
Name: count, dtype: int64

In [6]:
def get_category(subject):
    return subcat_to_cat[subject]

OOD_part = re.compile('The correct answer is [ABCD]')
OOD_part_len = len('The correct answer is ')

def get_pred(p):
    if OOD_part.search(p):
        return p[OOD_part_len]
    else:
        return p[0]

def processor(row: pd.DataFrame):
    generated_text = row['model_pred']['generated_text']
    generated_text = generated_text.strip()
    

    # generated_text	subject	pred	true	corr	category
    category = get_category(row['subject'])
    pred = get_pred(generated_text)
    true = chr(ord('A') + row['answer'])
    corr = int(pred == true)

    return {
        'generated_text': generated_text,
        'subject': row['subject'],
        'pred': pred,
        'true': true,
        'corr': corr,
        'category': category
    }

In [7]:
preds_dfs['LoRA-OOD 0 shot'] = preds_dfs['LoRA-OOD 0 shot'].apply(processor, axis=1, result_type='expand')
preds_dfs['LoRA-OOD 5 shot'] = preds_dfs['LoRA-OOD 5 shot'].apply(processor, axis=1, result_type='expand')
# preds_dfs['GSOFT-OOD 0 shot'] = preds_dfs['GSOFT-OOD 0 shot'].apply(processor, axis=1, result_type='expand')
preds_dfs['GSOFT-OOD 5 shot'] = preds_dfs['GSOFT-OOD 5 shot'].apply(processor, axis=1, result_type='expand')

In [8]:
preds_dfs['LoRA-OOD 0 shot'].head()

,generated_text,subject,pred,true,corr,category
0,The correct answer is D. 6. The degree of the ...,abstract_algebra,D,B,0,STEM
1,The correct answer is B. 2. The answer is B be...,abstract_algebra,B,C,0,STEM
2,"The correct answer is D. 0,4. The polynomial x^5",abstract_algebra,D,D,1,STEM
3,"The correct answer is A. True, True.\nStatemen...",abstract_algebra,A,B,0,STEM
4,The correct answer is B. 6x^2 + 4x +,abstract_algebra,B,B,1,STEM

In [9]:
preds_dfs['LoRA-OOD 5 shot'].head()

,generated_text,subject,pred,true,corr,category
0,B,abstract_algebra,B,B,1,STEM
1,C\nSolution: The order of p is 4. The order of S,abstract_algebra,C,C,1,STEM
2,D\nAnswer format: A/B/C/D. Full answer not nee...,abstract_algebra,D,D,1,STEM
3,D,abstract_algebra,D,B,0,STEM
4,B\nSolution: f(x) = 4x - 5 =,abstract_algebra,B,B,1,STEM

In [10]:
preds_dfs['GSOFT-OOD 5 shot'].head()

  generated_text           subject pred true  corr category
0              B  abstract_algebra    B    B     1     STEM
1              D  abstract_algebra    D    C     0     STEM
2              D  abstract_algebra    D    D     1     STEM
3              D  abstract_algebra    D    B     0     STEM
4           B. 6  abstract_algebra    B    B     1     STEM

In [11]:
acc_by_subjects = pd.DataFrame({
    'subject': list(set.union(
        *map(
            lambda df: set(df['subject']),
            preds_dfs.values()
        )
    ))
})

print(f"Subjects: {acc_by_subjects['subject']}")

for run_name, preds_df in preds_dfs.items():
    acc_df = preds_df[['subject', 'corr']].groupby(['subject'], as_index=False).mean()
    acc_df.rename(columns={'corr': run_name}, inplace=True)

    acc_by_subjects = acc_by_subjects.merge(
        acc_df,
        left_on='subject',
        right_on='subject',
        how='right'
    )

Subjects: 0                             human_aging
1                 professional_accounting
2              high_school_macroeconomics
3                         college_biology
4                         business_ethics
5     high_school_government_and_politics
6                         college_physics
7                       us_foreign_policy
8                  elementary_mathematics
9                       college_chemistry
10             high_school_microeconomics
11                             management
12                        world_religions
13                       medical_genetics
14                professional_psychology
15                 high_school_us_history
16                       machine_learning
17                 electrical_engineering
18                      computer_security
19                     clinical_knowledge
20                              marketing
21                     conceptual_physics
22                    high_school_biology
23                          jurisprudence
24                      international_law
25                  professional_medicine
26                    high_school_physics
27                             prehistory
28                       security_studies
29                           formal_logic
30                high_school_mathematics
31              high_school_world_history
32                           econometrics
33                        human_sexuality
34                      logical_fallacies
35                              nutrition
36               college_computer_science
37                                anatomy
38                       public_relations
39                        moral_scenarios
40                  high_school_chemistry
41           high_school_computer_science
42                              sociology
43           high_school_european_history
44                          miscellaneous
45                       professional_law
46                             philosophy
47                    college_mathematics
48                  high_school_geography
49                       abstract_algebra
50                 high_school_statistics
51                              astronomy
52                       college_medicine
53                               virology
54                 high_school_psychology
55                           global_facts
56                         moral_disputes
Name: subject, dtype: object

In [12]:
acc_by_subjects

,subject,raw 0 shot,raw 5 shot,LoRA 0 shot,LoRA 5 shot,LoRA-OOD 0 shot,LoRA-OOD 5 shot,GSOFT-OOD 5 shot
0,abstract_algebra,0.350000,0.310000,0.310000,0.340000,0.260000,0.300000,0.300000
1,anatomy,0.674074,0.666667,0.629630,0.614815,0.607407,0.637037,0.681481
2,astronomy,0.750000,0.723684,0.717105,0.730263,0.723684,0.677632,0.756579
3,business_ethics,0.660000,0.670000,0.610000,0.650000,0.730000,0.640000,0.740000
4,clinical_knowledge,0.716981,0.747170,0.743396,0.769811,0.698113,0.698113,0.724528
5,college_biology,0.715278,0.756944,0.784722,0.791667,0.715278,0.729167,0.784722
6,college_chemistry,0.450000,0.460000,0.480000,0.490000,0.410000,0.400000,0.440000
7,college_computer_science,0.470000,0.570000,0.470000,0.540000,0.490000,0.470000,0.490000
8,college_mathematics,0.350000,0.350000,0.280000,0.380000,0.260000,0.270000,0.350000
9,college_medicine,0.618497,0.641618,0.664740,0.647399,0.560694,0.566474,0.606936
10,college_physics,0.441176,0.401961,0.460784,0.529412,0.431373,0.411765,0.411765
11,computer_security,0.770000,0.760000,0.730000,0.790000,0.770000,0.760000,0.800000
12,conceptual_physics,0.548936,0.591489,0.570213,0.557447,0.557447,0.565957,0.578723
13,econometrics,0.500000,0.570175,0.552632,0.561404,0.456140,0.543860,0.587719
14,electrical_engineering,0.579310,0.606897,0.600000,0.606897,0.531034,0.537931,0.606897
15,elementary_mathematics,0.460317,0.441799,0.489418,0.455026,0.425926,0.412698,0.439153
16,formal_logic,0.388889,0.500000,0.468254,0.500000,0.428571,0.396825,0.460317
17,global_facts,0.420000,0.420000,0.400000,0.420000,0.440000,0.460000,0.470000
18,high_school_biology,0.790323,0.796774,0.774194,0.774194,0.770968,0.729032,0.745161
19,high_school_chemistry,0.453202,0.507389,0.512315,0.546798,0.507389,0.492611,0.551724
20,high_school_computer_science,0.650000,0.700000,0.740000,0.760000,0.670000,0.700000,0.680000
21,high_school_european_history,0.715152,0.769697,0.757576,0.757576,0.763636,0.721212,0.757576
22,high_school_geography,0.777778,0.813131,0.803030,0.818182,0.787879,0.772727,0.808081
23,high_school_government_and_politics,0.849741,0.911917,0.901554,0.901554,0.829016,0.829016,0.865285
24,high_school_macroeconomics,0.610256,0.671795,0.610256,0.648718,0.620513,0.612821,0.633333
25,high_school_mathematics,0.329630,0.351852,0.270370,0.370370,0.192593,0.329630,0.325926
26,high_school_microeconomics,0.731092,0.760504,0.710084,0.747899,0.705882,0.689076,0.747899
27,high_school_physics,0.357616,0.430464,0.403974,0.437086,0.384106,0.430464,0.483444
28,high_school_psychology,0.823853,0.831193,0.853211,0.858716,0.805505,0.787156,0.827523
29,high_school_statistics,0.481481,0.518519,0.541667,0.555556,0.495370,0.486111,0.458333
30,high_school_us_history,0.759804,0.764706,0.813725,0.803922,0.789216,0.769608,0.774510
31,high_school_world_history,0.776371,0.835443,0.827004,0.848101,0.772152,0.755274,0.827004
32,human_aging,0.690583,0.735426,0.681614,0.730942,0.672646,0.708520,0.713004
33,human_sexuality,0.740458,0.778626,0.725191,0.778626,0.679389,0.740458,0.717557
34,international_law,0.735537,0.785124,0.776860,0.752066,0.719008,0.727273,0.785124
35,jurisprudence,0.703704,0.768519,0.768519,0.768519,0.731481,0.768519,0.740741
36,logical_fallacies,0.730061,0.748466,0.699387,0.705521,0.687117,0.656442,0.766871
37,machine_learning,0.428571,0.526786,0.544643,0.526786,0.482143,0.535714,0.526786
38,management,0.786408,0.805825,0.834951,0.844660,0.796117,0.776699,0.844660
39,marketing,0.871795,0.910256,0.901709,0.910256,0.884615,0.867521,0.880342
40,medical_genetics,0.740000,0.780000,0.780000,0.730000,0.760000,0.700000,0.740000
41,miscellaneous,0.809706,0.819923,0.812261,0.821201,0.800766,0.798212,0.813538
42,moral_disputes,0.656069,0.760116,0.667630,0.736994,0.661850,0.632948,0.696532
43,moral_scenarios,0.271508,0.469274,0.239106,0.370950,0.293855,0.418994,0.440223
44,nutrition,0.732026,0.764706,0.735294,0.741830,0.712418,0.663399,0.748366
45,philosophy,0.681672,0.733119,0.720257,0.723473,0.681672,0.672026,0.710611
46,prehistory,0.719136,0.734568,0.709877,0.756173,0.719136,0.700617,0.740741
47,professional_accounting,0.510638,0.542553,0.482270,0.485816,0.503546,0.489362,0.514184
48,professional_law,0.415906,0.462190,0.482399,0.485658,0.415906,0.398957,0.451108
49,professional_medicine,0.746324,0.694853,0.731618,0.746324,0.654412,0.658088,0.661765
50,professional_psychology,0.633987,0.694444,0.696078,0.718954,0.668301,0.656863,0.699346
51,public_relations,0.645455,0.672727,0.700000,0.681818,0.709091,0.672727,0.654545
52,security_studies,0.702041,0.734694,0.722449,0.726531,0.710204,0.706122,0.722449
53,sociology,0.850746,0.850746,0.845771,0.855721,0.835821,0.791045,0.820896
54,us_foreign_policy,0.860000,0.840000,0.850000,0.910000,0.860000,0.850000,0.850000
55,virology,0.463855,0.506024,0.469880,0.493976,0.469880,0.506024,0.524096
56,world_religions,0.801170,0.812865,0.824561,0.818713,0.783626,0.777778,0.795322

In [13]:
acc_by_categories = pd.DataFrame({
    'category': list(set.union(
        *map(
            lambda df: set(df['category']),
            preds_dfs.values()
        )
    ))
})

for run_name, preds_df in preds_dfs.items():
    acc_df = preds_df[['category', 'corr']].groupby(['category'], as_index=False).mean()
    acc_df.rename(columns={'corr': run_name}, inplace=True)

    acc_by_categories = acc_by_categories.merge(
        acc_df,
        left_on='category',
        right_on='category',
        how='right'
    )

In [14]:
acc_by_categories.loc[:, list(filter(
    lambda s: ('5 shot' not in s),
    acc_by_categories.columns
))]

                          category  raw 0 shot  LoRA 0 shot  LoRA-OOD 0 shot
0                             STEM    0.525182     0.540755         0.505302
1                       humanities    0.527099     0.556217         0.533688
2  other (business, health, misc.)    0.706663     0.709130         0.690623
3                  social sciences    0.721807     0.746831         0.721807

In [15]:
acc_by_categories.loc[:, list(filter(
    lambda s: ('0 shot' not in s),
    acc_by_categories.columns
))]

,category,raw 5 shot,LoRA 5 shot,LoRA-OOD 5 shot,GSOFT-OOD 5 shot
0,STEM,0.546720,0.561962,0.514248,0.539430
1,humanities,0.603826,0.591711,0.543677,0.586823
2,"other (business, health, misc.)",0.724244,0.719926,0.684454,0.713757
3,social sciences,0.758531,0.766006,0.714007,0.744556

In [16]:
total_res = pd.DataFrame(columns=['run_name', 'accuracy', 'correctness'])

for run_name, preds_df in preds_dfs.items():
    total_accuracy = preds_df['corr'].mean()
    total_correctness = (preds_df['pred'] != 'I').mean()

    total_res = pd.concat([
        total_res,
        pd.DataFrame({
            'run_name': [run_name],
            'accuracy': [total_accuracy],
            'correctness': [total_correctness],
        })
    ])

C:\Users\Vladimir\AppData\Local\Temp\ipykernel_27408\2066953499.py:7: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  total_res = pd.concat([

In [17]:
total_res

           run_name  accuracy  correctness
0        raw 0 shot  0.610810     0.997151
0        raw 5 shot  0.653255     0.999217
0       LoRA 0 shot  0.629967     0.992024
0       LoRA 5 shot  0.653112     1.000000
0   LoRA-OOD 0 shot  0.605042     1.000000
0   LoRA-OOD 5 shot  0.607178     1.000000
0  GSOFT-OOD 5 shot  0.640507     1.000000